# ESCRIBIR UN PROGRAMA QUE PREGUNTE AL USUARIO LAS VENTAS DE UN RANGO DE PERÍODO ANUAL (EN AÑOS) Y QUE MUESTRE POR PANTALLA UN DIAGRAMA DE LÍNEAS CON LA EVOLUCIÓN DE LAS VENTAS.

# SOLUCIÓN:

# IMPORTAREMOS LA LIBRERÍA "matplotlib" MÁS UN "pyplot" JUNTO CON EL ALIAS RESPECTIVO ("plt")...

import matplotlib.pyplot as plt

# PREGUNTAMOS POR EL AÑO INICIAL:

inicio = int(input('INTRODUCE EL AÑO INICIAL: '))

# REPETIMOS EL PROCESO PERO CON EL AÑO FINAL:

final = int(input('INTRODUCE EL AÑO FINAL: '))

# LUEGO, DEFINIMOS UN DICCIONARIO VACÍO PARA GUARDAR LAS VENTAS DE CADA AÑO (PERÍODO ANUAL)...

ventas = {}

# 1.- DEFINIMOS UN BUCLE ITERATIVO PARA CONSULTAR LAS VENTAS ANUALES Y LUEGO GUARDARLAS DENTRO DEL DICCIONARIO YA CREADO.

# 2.- ADEMÁS, LA VARIABLE "i" TOMA VALORES ANUALES DESDE EL AÑO INICIAL HASTA EL AÑO FINAL...

for i in range(inicio, final + 1):

    # PREGUNTAMOS POR LAS VENTAS DE UN AÑO EN "i" Y LAS GUARDAMOS DENTRO DE UN DICCIONARIO CON LA CLAVE EL AÑO Y EL VALOR DE LAS VENTAS...

    ventas[i] = float(input('INTRODUCE LAS VENTAS DEL AÑO ' + str(i) + ': '))

# LUEGO, DEFINIMOS LA FIGURA Y LOS EJES DEL GRÁFICO CON LA LIBRERÍA "Matplotlib"...

fig, ax = plt.subplots()

# DIBUJAMOS UNA LÍNEA CON LAS VENTAS RESPECTIVAS A PARTIR DE UN DICCIONARIO DE DICHAS VENTAS...

ax.plot(ventas.keys(), ventas.values())

# POR ÚLTIMO, MOSTRAREMOS EL GRÁFICO POR PANTALLA...

plt.show()