# ESCRIBIR UNA FUNCIÓN QUE RECIBA UN DICCIONARIO CON LAS NOTAS DE LAS ASIGNATURAS DE UN CURSO Y 
# UN "string" MÁS EL NOMBRE DE UN COLOR CUALQUIERA Y QUE DEVUALVA UN GRÁFICO DE BARRAS DE LAS 
# NOTAS EN EL COLOR DADO.

# SOLUCIÓN:

# IMPORTAREMOS LA LIBRERÍA "Matplotlib"...

import matplotlib.pyplot as plt

# DESPUÉS CONSTRUIREMOS UN GRÁFICO DE BARRAS MEDIANTE LA SIGUIENTE FUNCIÓN:

def grafico_barras_calificaciones(calificaciones, color):

    '''FUNCIÓN QUE CONSTRUYE UN GRÁFICO DE BARRAS CON LAS CALIFICACIONES DE LAS ASIGNATURAS DE UN CURSO.
    
    PARÁMETROS:
    
       - CALIFICACIONES: ES UN DICCIONARIO FORMADO POR PARES CON CLAVE EL NOMBRE DE LA ASIGNATURA Y EL VALOR EN LA CUAL ES LA CALIFICACIÓN ASOCIADA.
       - BARNIZ: ES UNA CADENA CON EL COLOR DE LAS BARRAS DEL GRÁFICO.
        
    PARÁMETROS DE SALIDA:
     
       - UN DIAGRAMA DE BARRAS CON LAS CALIFICACIONES DEL DICCIONARIO ACORDE AL COLOR SOLICITADO.
    '''

    # DEFINIMOS LA FIGURA Y LOS EJES DEL GRÁFICO CON LA LIBRERÍA "Matplotlib"...

    fig, ax = plt.subplots()

    # DIBUJAMOS LAS BARRAS CON LAS CALIFICACIONES A PARTIR DEL DICCIONARIO...

    ax.bar(calificaciones.keys(), calificaciones.values(), color = color)

    return ax

# DETALLE DE CALIFICACIONES POR CADA ASIGNATURA:

calificaciones = {'PROGRAMACIÓN': 6, 'MATEMÁTICAS': 5, 'ECONOMÍA': 7, 'HISTORIA': 4}

# DIBUJAMOS EL GRÁFICO DE BARRAS SEÑALADO ANTERIORMENTE:

grafico_barras_calificaciones(calificaciones, 'orange')

# MUESTRA EL GRÁFICO POR PANTALLA...

plt.show()